In [2]:
import pandas as pd
import numpy as np

In [3]:
dataframe = pd.read_csv('Train.csv')

In [4]:
dataframe.shape

(8523, 12)

In [5]:
dataframe.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [6]:
x_train = dataframe.drop(['Item_Outlet_Sales'],axis=1)

In [7]:
y_train = dataframe.drop(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type'],axis=1)

In [8]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [9]:
# x_train = x_train.fillna(x_train['Item_Weight'].value_counts().index[0])
print(x_train.isnull().sum())

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [10]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 11 columns):
Item_Identifier              8523 non-null object
Item_Weight                  7060 non-null float64
Item_Fat_Content             8523 non-null object
Item_Visibility              8523 non-null float64
Item_Type                    8523 non-null object
Item_MRP                     8523 non-null float64
Outlet_Identifier            8523 non-null object
Outlet_Establishment_Year    8523 non-null int64
Outlet_Size                  6113 non-null object
Outlet_Location_Type         8523 non-null object
Outlet_Type                  8523 non-null object
dtypes: float64(3), int64(1), object(7)
memory usage: 732.5+ KB

In [11]:
import copy

In [12]:
x_train_cat = x_train.select_dtypes(include=['object']).copy()

In [13]:
x_train_cat.head

<bound method NDFrame.head of      Item_Identifier Item_Fat_Content              Item_Type  \
0              FDA15          Low Fat                  Dairy
1              DRC01          Regular            Soft Drinks
2              FDN15          Low Fat                   Meat
3              FDX07          Regular  Fruits and Vegetables
4              NCD19          Low Fat              Household
5              FDP36          Regular           Baking Goods
6              FDO10          Regular            Snack Foods
7              FDP10          Low Fat            Snack Foods
8              FDH17          Regular           Frozen Foods
9              FDU28          Regular           Frozen Foods
10             FDY07          Low Fat  Fruits and Vegetables
11             FDA03          Regular                  Dairy
12             FDX32          Regular  Fruits and Vegetables
13             FDS46          Regular            Snack Foods
14             FDF32          Low Fat  Fruits and Vegetables
15             FDP49          Regular              Breakfast
16             NCB42          Low Fat     Health and Hygiene
17             FDP49          Regular              Breakfast
18             DRI11          Low Fat            Hard Drinks
19             FDU02          Low Fat                  Dairy
20             FDN22          Regular            Snack Foods
21             FDW12          Regular           Baking Goods
22             NCB30          Low Fat              Household
23             FDC37          Low Fat           Baking Goods
24             FDR28          Regular           Frozen Foods
25             NCD06          Low Fat              Household
26             FDV10          Regular            Snack Foods
27             DRJ59          low fat            Hard Drinks
28             FDE51          Regular                  Dairy
29             FDC14          Regular                 Canned
...              ...              ...                    ...
8493           FDP21          Regular            Snack Foods
8494           NCI54          Low Fat              Household
8495           FDE22          Low Fat            Snack Foods
8496           FDJ57          Regular                Seafood
8497           FDT08          Low Fat  Fruits and Vegetables
8498           NCP54          Low Fat              Household
8499           NCK53          Low Fat     Health and Hygiene
8500           NCQ42          Low Fat              Household
8501           FDW21          Regular            Snack Foods
8502           NCH43          Low Fat              Household
8503           FDQ44          Low Fat  Fruits and Vegetables
8504           NCN18          Low Fat              Household
8505           FDB46          Regular            Snack Foods
8506           DRF37          Low Fat            Soft Drinks
8507           FDN28          Regular           Frozen Foods
8508           FDW31          Regular  Fruits and Vegetables
8509           FDG45          Low Fat  Fruits and Vegetables
8510           FDN58          Regular            Snack Foods
8511           FDF05          Low Fat           Frozen Foods
8512           FDR26          Low Fat                  Dairy
8513           FDH31          Regular                   Meat
8514           FDA01          Regular                 Canned
8515           FDH24          Low Fat           Baking Goods
8516           NCJ19          Low Fat                 Others
8517           FDF53              reg           Frozen Foods
8518           FDF22          Low Fat            Snack Foods
8519           FDS36          Regular           Baking Goods
8520           NCJ29          Low Fat     Health and Hygiene
8521           FDN46          Regular            Snack Foods
8522           DRG01          Low Fat            Soft Drinks

     Outlet_Identifier Outlet_Size Outlet_Location_Type        Outlet_Type
0               OUT049      Medium               Tier 1  Supermarket Type1
1               OUT018      Medium               Tier 3  Supermarket Type2
2               OUT049      Medium               Tier 1  Supermarket Type1
3               OUT010         NaN               Tier 3      Grocery Store
4               OUT013        High               Tier 3  Supermarket Type1
5               OUT018      Medium               Tier 3  Supermarket Type2
6               OUT013        High               Tier 3  Supermarket Type1
7               OUT027      Medium               Tier 3  Supermarket Type3
8               OUT045         NaN               Tier 2  Supermarket Type1
9               OUT017         NaN               Tier 2  Supermarket Type1
10              OUT049      Medium               Tier 1  Supermarket Type1
11              OUT046       Small               Tier 1  Supermarket Type1
12              OUT049      Medium               Tier 1  Supermarket Type1
13              OUT046       Small               Tier 1  Supermarket Type1
14              OUT013        High               Tier 3  Supermarket Type1
15              OUT046       Small               Tier 1  Supermarket Type1
16              OUT018      Medium               Tier 3  Supermarket Type2
17              OUT049      Medium               Tier 1  Supermarket Type1
18              OUT027      Medium               Tier 3  Supermarket Type3
19              OUT035       Small               Tier 2  Supermarket Type1
20              OUT013        High               Tier 3  Supermarket Type1
21              OUT027      Medium               Tier 3  Supermarket Type3
22              OUT035       Small               Tier 2  Supermarket Type1
23              OUT019       Small               Tier 1      Grocery Store
24              OUT046       Small               Tier 1  Supermarket Type1
25              OUT017         NaN               Tier 2  Supermarket Type1
26              OUT035       Small               Tier 2  Supermarket Type1
27              OUT013        High               Tier 3  Supermarket Type1
28              OUT010         NaN               Tier 3      Grocery Store
29              OUT019       Small               Tier 1      Grocery Store
...                ...         ...                  ...                ...
8493            OUT017         NaN               Tier 2  Supermarket Type1
8494            OUT017         NaN               Tier 2  Supermarket Type1
8495            OUT035       Small               Tier 2  Supermarket Type1
8496            OUT017         NaN               Tier 2  Supermarket Type1
8497            OUT035       Small               Tier 2  Supermarket Type1
8498            OUT018      Medium               Tier 3  Supermarket Type2
8499            OUT035       Small               Tier 2  Supermarket Type1
8500            OUT017         NaN               Tier 2  Supermarket Type1
8501            OUT017         NaN               Tier 2  Supermarket Type1
8502            OUT045         NaN               Tier 2  Supermarket Type1
8503            OUT035       Small               Tier 2  Supermarket Type1
8504            OUT027      Medium               Tier 3  Supermarket Type3
8505            OUT018      Medium               Tier 3  Supermarket Type2
8506            OUT018      Medium               Tier 3  Supermarket Type2
8507            OUT035       Small               Tier 2  Supermarket Type1
8508            OUT045         NaN               Tier 2  Supermarket Type1
8509            OUT010         NaN               Tier 3      Grocery Store
8510            OUT035       Small               Tier 2  Supermarket Type1
8511            OUT018      Medium               Tier 3  Supermarket Type2
8512            OUT013        High               Tier 3  Supermarket Type1
8513            OUT035       Small               Tier 2  Supermarket Type1
8514            OUT045         NaN               Tier 2  Supermarket Type1
8515            OUT018      Medium               Tier 3  Supermarket Type2
8516            OUT018      Medium               Tier 3  Supermarket Type2
8517            OUT046       Small               Tier 1  Supermarket Type1
8518            OUT013        High               Tier 3  Supermarket Type1
8519            OUT045         NaN               Tier 2  Supermarket Type1
8520            OUT035       Small               Tier 2  Supermarket Type1
8521            OUT018      Medium               Tier 3  Supermarket Type2
8522            OUT046       Small               Tier 1  Supermarket Type1

[8523 rows x 7 columns]>

In [14]:
x_train_cat.isnull().sum()

Item_Identifier            0
Item_Fat_Content           0
Item_Type                  0
Outlet_Identifier          0
Outlet_Size             2410
Outlet_Location_Type       0
Outlet_Type                0
dtype: int64

In [15]:
x_train_cat=x_train_cat.fillna(x_train_cat['Outlet_Size'].value_counts().index[0])

In [16]:
x_train_cat.isnull().sum()

Item_Identifier         0
Item_Fat_Content        0
Item_Type               0
Outlet_Identifier       0
Outlet_Size             0
Outlet_Location_Type    0
Outlet_Type             0
dtype: int64

In [17]:
print(x_train_cat['Outlet_Type'].value_counts().count())
print(x_train_cat['Item_Identifier'].value_counts().count())
print(x_train_cat['Item_Fat_Content'].value_counts().count())

4
1559
5

In [18]:
labels = x_train_cat['Item_Identifier'].astype('category').cat.categories.tolist()
replace_map_comp = {'Item_Identifier' : {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}

# print(replace_map_comp)
x_train_cat.replace(replace_map_comp,inplace=True)
x_train_cat

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,157,Low Fat,Dairy,OUT049,Medium,Tier 1,Supermarket Type1
1,9,Regular,Soft Drinks,OUT018,Medium,Tier 3,Supermarket Type2
2,663,Low Fat,Meat,OUT049,Medium,Tier 1,Supermarket Type1
3,1122,Regular,Fruits and Vegetables,OUT010,Medium,Tier 3,Grocery Store
4,1298,Low Fat,Household,OUT013,High,Tier 3,Supermarket Type1
5,759,Regular,Baking Goods,OUT018,Medium,Tier 3,Supermarket Type2
6,697,Regular,Snack Foods,OUT013,High,Tier 3,Supermarket Type1
7,739,Low Fat,Snack Foods,OUT027,Medium,Tier 3,Supermarket Type3
8,441,Regular,Frozen Foods,OUT045,Medium,Tier 2,Supermarket Type1
9,991,Regular,Frozen Foods,OUT017,Medium,Tier 2,Supermarket Type1
10,1172,Low Fat,Fruits and Vegetables,OUT049,Medium,Tier 1,Supermarket Type1
11,148,Regular,Dairy,OUT046,Small,Tier 1,Supermarket Type1
12,1143,Regular,Fruits and Vegetables,OUT049,Medium,Tier 1,Supermarket Type1
13,905,Regular,Snack Foods,OUT046,Small,Tier 1,Supermarket Type1
14,376,Low Fat,Fruits and Vegetables,OUT013,High,Tier 3,Supermarket Type1
15,768,Regular,Breakfast,OUT046,Small,Tier 1,Supermarket Type1
16,1281,Low Fat,Health and Hygiene,OUT018,Medium,Tier 3,Supermarket Type2
17,768,Regular,Breakfast,OUT049,Medium,Tier 1,Supermarket Type1
18,80,Low Fat,Hard Drinks,OUT027,Medium,Tier 3,Supermarket Type3
19,969,Low Fat,Dairy,OUT035,Small,Tier 2,Supermarket Type1
20,667,Regular,Snack Foods,OUT013,High,Tier 3,Supermarket Type1
21,1077,Regular,Baking Goods,OUT027,Medium,Tier 3,Supermarket Type3
22,1279,Low Fat,Household,OUT035,Small,Tier 2,Supermarket Type1
23,260,Low Fat,Baking Goods,OUT019,Small,Tier 1,Grocery Store
24,844,Regular,Frozen Foods,OUT046,Small,Tier 1,Supermarket Type1
25,1295,Low Fat,Household,OUT017,Medium,Tier 2,Supermarket Type1
26,1025,Regular,Snack Foods,OUT035,Small,Tier 2,Supermarket Type1
27,102,low fat,Hard Drinks,OUT013,High,Tier 3,Supermarket Type1
28,351,Regular,Dairy,OUT010,Medium,Tier 3,Grocery Store
29,245,Regular,Canned,OUT019,Small,Tier 1,Grocery Store
...,...,...,...,...,...,...,...
8493,747,Regular,Snack Foods,OUT017,Medium,Tier 2,Supermarket Type1
8494,1351,Low Fat,Household,OUT017,Medium,Tier 2,Supermarket Type1
8495,331,Low Fat,Snack Foods,OUT035,Small,Tier 2,Supermarket Type1
8496,541,Regular,Seafood,OUT017,Medium,Tier 2,Supermarket Type1
8497,923,Low Fat,Fruits and Vegetables,OUT035,Small,Tier 2,Supermarket Type1
8498,1451,Low Fat,Household,OUT018,Medium,Tier 3,Supermarket Type2
8499,1374,Low Fat,Health and Hygiene,OUT035,Small,Tier 2,Supermarket Type1
8500,1462,Low Fat,Household,OUT017,Medium,Tier 2,Supermarket Type1
8501,1084,Regular,Snack Foods,OUT017,Medium,Tier 2,Supermarket Type1
8502,1340,Low Fat,Household,OUT045,Medium,Tier 2,Supermarket Type1
8503,807,Low Fat,Fruits and Vegetables,OUT035,Small,Tier 2,Supermarket Type1
8504,1411,Low Fat,Household,OUT027,Medium,Tier 3,Supermarket Type3
8505,225,Regular,Snack Foods,OUT018,Medium,Tier 3,Supermarket Type2
8506,46,Low Fat,Soft Drinks,OUT018,Medium,Tier 3,Supermarket Type2
8507,672,Regular,Frozen Foods,OUT035,Small,Tier 2,Supermarket Type1
8508,1092,Regular,Fruits and Vegetables,OUT045,Medium,Tier 2,Supermarket Type1
8509,421,Low Fat,Fruits and Vegetables,OUT010,Medium,Tier 3,Grocery Store
8510,690,Regular,Snack Foods,OUT035,Small,Tier 2,Supermarket Type1
8511,360,Low Fat,Frozen Foods,OUT018,Medium,Tier 3,Supermarket Type2
8512,842,Low Fat,Dairy,OUT013,High,Tier 3,Supermarket Type1
8513,450,Regular,Meat,OUT035,Small,Tier 2,Supermarket Type1
8514,146,Regular,Canned,OUT045,Medium,Tier 2,Supermarket Type1
8515,446,Low Fat,Baking Goods,OUT018,Medium,Tier 3,Supermarket Type2
8516,1357,Low Fat,Others,OUT018,Medium,Tier 3,Supermarket Type2
8517,390,reg,Frozen Foods,OUT046,Small,Tier 1,Supermarket Type1
8518,371,Low Fat,Snack Foods,OUT013,High,Tier 3,Supermarket Type1
8519,898,Regular,Baking Goods,OUT045,Medium,Tier 2,Supermarket Type1
8520,1358,Low Fat,Health and Hygiene,OUT035,Small,Tier 2,Supermarket Type1
8521,682,Regular,Snack Foods,OUT018,Medium,Tier 3,Supermarket Type2
8522,51,Low Fat,Soft Drinks,OUT046,Small,Tier 1,Supermarket Type1

In [19]:
x_train_cat.columns

Index(['Item_Identifier', 'Item_Fat_Content', 'Item_Type', 'Outlet_Identifier',
       'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type'],
      dtype='object')

In [20]:
labels = x_train_cat['Item_Fat_Content'].astype('category').cat.categories.tolist()
replace_map_comp = {'Item_Fat_Content' : {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}

# print(replace_map_comp)
x_train_cat.replace(replace_map_comp,inplace=True)
x_train_cat

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,157,2,Dairy,OUT049,Medium,Tier 1,Supermarket Type1
1,9,3,Soft Drinks,OUT018,Medium,Tier 3,Supermarket Type2
2,663,2,Meat,OUT049,Medium,Tier 1,Supermarket Type1
3,1122,3,Fruits and Vegetables,OUT010,Medium,Tier 3,Grocery Store
4,1298,2,Household,OUT013,High,Tier 3,Supermarket Type1
5,759,3,Baking Goods,OUT018,Medium,Tier 3,Supermarket Type2
6,697,3,Snack Foods,OUT013,High,Tier 3,Supermarket Type1
7,739,2,Snack Foods,OUT027,Medium,Tier 3,Supermarket Type3
8,441,3,Frozen Foods,OUT045,Medium,Tier 2,Supermarket Type1
9,991,3,Frozen Foods,OUT017,Medium,Tier 2,Supermarket Type1
10,1172,2,Fruits and Vegetables,OUT049,Medium,Tier 1,Supermarket Type1
11,148,3,Dairy,OUT046,Small,Tier 1,Supermarket Type1
12,1143,3,Fruits and Vegetables,OUT049,Medium,Tier 1,Supermarket Type1
13,905,3,Snack Foods,OUT046,Small,Tier 1,Supermarket Type1
14,376,2,Fruits and Vegetables,OUT013,High,Tier 3,Supermarket Type1
15,768,3,Breakfast,OUT046,Small,Tier 1,Supermarket Type1
16,1281,2,Health and Hygiene,OUT018,Medium,Tier 3,Supermarket Type2
17,768,3,Breakfast,OUT049,Medium,Tier 1,Supermarket Type1
18,80,2,Hard Drinks,OUT027,Medium,Tier 3,Supermarket Type3
19,969,2,Dairy,OUT035,Small,Tier 2,Supermarket Type1
20,667,3,Snack Foods,OUT013,High,Tier 3,Supermarket Type1
21,1077,3,Baking Goods,OUT027,Medium,Tier 3,Supermarket Type3
22,1279,2,Household,OUT035,Small,Tier 2,Supermarket Type1
23,260,2,Baking Goods,OUT019,Small,Tier 1,Grocery Store
24,844,3,Frozen Foods,OUT046,Small,Tier 1,Supermarket Type1
25,1295,2,Household,OUT017,Medium,Tier 2,Supermarket Type1
26,1025,3,Snack Foods,OUT035,Small,Tier 2,Supermarket Type1
27,102,4,Hard Drinks,OUT013,High,Tier 3,Supermarket Type1
28,351,3,Dairy,OUT010,Medium,Tier 3,Grocery Store
29,245,3,Canned,OUT019,Small,Tier 1,Grocery Store
...,...,...,...,...,...,...,...
8493,747,3,Snack Foods,OUT017,Medium,Tier 2,Supermarket Type1
8494,1351,2,Household,OUT017,Medium,Tier 2,Supermarket Type1
8495,331,2,Snack Foods,OUT035,Small,Tier 2,Supermarket Type1
8496,541,3,Seafood,OUT017,Medium,Tier 2,Supermarket Type1
8497,923,2,Fruits and Vegetables,OUT035,Small,Tier 2,Supermarket Type1
8498,1451,2,Household,OUT018,Medium,Tier 3,Supermarket Type2
8499,1374,2,Health and Hygiene,OUT035,Small,Tier 2,Supermarket Type1
8500,1462,2,Household,OUT017,Medium,Tier 2,Supermarket Type1
8501,1084,3,Snack Foods,OUT017,Medium,Tier 2,Supermarket Type1
8502,1340,2,Household,OUT045,Medium,Tier 2,Supermarket Type1
8503,807,2,Fruits and Vegetables,OUT035,Small,Tier 2,Supermarket Type1
8504,1411,2,Household,OUT027,Medium,Tier 3,Supermarket Type3
8505,225,3,Snack Foods,OUT018,Medium,Tier 3,Supermarket Type2
8506,46,2,Soft Drinks,OUT018,Medium,Tier 3,Supermarket Type2
8507,672,3,Frozen Foods,OUT035,Small,Tier 2,Supermarket Type1
8508,1092,3,Fruits and Vegetables,OUT045,Medium,Tier 2,Supermarket Type1
8509,421,2,Fruits and Vegetables,OUT010,Medium,Tier 3,Grocery Store
8510,690,3,Snack Foods,OUT035,Small,Tier 2,Supermarket Type1
8511,360,2,Frozen Foods,OUT018,Medium,Tier 3,Supermarket Type2
8512,842,2,Dairy,OUT013,High,Tier 3,Supermarket Type1
8513,450,3,Meat,OUT035,Small,Tier 2,Supermarket Type1
8514,146,3,Canned,OUT045,Medium,Tier 2,Supermarket Type1
8515,446,2,Baking Goods,OUT018,Medium,Tier 3,Supermarket Type2
8516,1357,2,Others,OUT018,Medium,Tier 3,Supermarket Type2
8517,390,5,Frozen Foods,OUT046,Small,Tier 1,Supermarket Type1
8518,371,2,Snack Foods,OUT013,High,Tier 3,Supermarket Type1
8519,898,3,Baking Goods,OUT045,Medium,Tier 2,Supermarket Type1
8520,1358,2,Health and Hygiene,OUT035,Small,Tier 2,Supermarket Type1
8521,682,3,Snack Foods,OUT018,Medium,Tier 3,Supermarket Type2
8522,51,2,Soft Drinks,OUT046,Small,Tier 1,Supermarket Type1

In [21]:
x_train_cat.columns

Index(['Item_Identifier', 'Item_Fat_Content', 'Item_Type', 'Outlet_Identifier',
       'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type'],
      dtype='object')

In [22]:
labels = x_train_cat['Item_Type'].astype('category').cat.categories.tolist()
replace_map_comp = {'Item_Type' : {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}

# print(replace_map_comp)
x_train_cat.replace(replace_map_comp,inplace=True)

In [23]:
labels = x_train_cat['Outlet_Identifier'].astype('category').cat.categories.tolist()
replace_map_comp = {'Outlet_Identifier' : {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}

# print(replace_map_comp)
x_train_cat.replace(replace_map_comp,inplace=True)

In [24]:
labels = x_train_cat['Outlet_Size'].astype('category').cat.categories.tolist()
replace_map_comp = {'Outlet_Size' : {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}

# print(replace_map_comp)
x_train_cat.replace(replace_map_comp,inplace=True)

In [25]:
labels = x_train_cat['Outlet_Location_Type'].astype('category').cat.categories.tolist()
replace_map_comp = {'Outlet_Location_Type' : {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}

# print(replace_map_comp)
x_train_cat.replace(replace_map_comp,inplace=True)

In [26]:
labels = x_train_cat['Outlet_Type'].astype('category').cat.categories.tolist()
replace_map_comp = {'Outlet_Type' : {k: v for k,v in zip(labels,list(range(1,len(labels)+1)))}}

# print(replace_map_comp)
x_train_cat.replace(replace_map_comp,inplace=True)

In [27]:
x_train_cat

,Item_Identifier,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,157,2,5,10,2,1,2
1,9,3,15,4,2,3,3
2,663,2,11,10,2,1,2
3,1122,3,7,1,2,3,1
4,1298,2,10,2,1,3,2
5,759,3,1,4,2,3,3
6,697,3,14,2,1,3,2
7,739,2,14,6,2,3,4
8,441,3,6,8,2,2,2
9,991,3,6,3,2,2,2
10,1172,2,7,10,2,1,2
11,148,3,5,9,3,1,2
12,1143,3,7,10,2,1,2
13,905,3,14,9,3,1,2
14,376,2,7,2,1,3,2
15,768,3,3,9,3,1,2
16,1281,2,9,4,2,3,3
17,768,3,3,10,2,1,2
18,80,2,8,6,2,3,4
19,969,2,5,7,3,2,2
20,667,3,14,2,1,3,2
21,1077,3,1,6,2,3,4
22,1279,2,10,7,3,2,2
23,260,2,1,5,3,1,1
24,844,3,6,9,3,1,2
25,1295,2,10,3,2,2,2
26,1025,3,14,7,3,2,2
27,102,4,8,2,1,3,2
28,351,3,5,1,2,3,1
29,245,3,4,5,3,1,1
...,...,...,...,...,...,...,...
8493,747,3,14,3,2,2,2
8494,1351,2,10,3,2,2,2
8495,331,2,14,7,3,2,2
8496,541,3,13,3,2,2,2
8497,923,2,7,7,3,2,2
8498,1451,2,10,4,2,3,3
8499,1374,2,9,7,3,2,2
8500,1462,2,10,3,2,2,2
8501,1084,3,14,3,2,2,2
8502,1340,2,10,8,2,2,2
8503,807,2,7,7,3,2,2
8504,1411,2,10,6,2,3,4
8505,225,3,14,4,2,3,3
8506,46,2,15,4,2,3,3
8507,672,3,6,7,3,2,2
8508,1092,3,7,8,2,2,2
8509,421,2,7,1,2,3,1
8510,690,3,14,7,3,2,2
8511,360,2,6,4,2,3,3
8512,842,2,5,2,1,3,2
8513,450,3,11,7,3,2,2
8514,146,3,4,8,2,2,2
8515,446,2,1,4,2,3,3
8516,1357,2,12,4,2,3,3
8517,390,5,6,9,3,1,2
8518,371,2,14,2,1,3,2
8519,898,3,1,8,2,2,2
8520,1358,2,9,7,3,2,2
8521,682,3,14,4,2,3,3
8522,51,2,15,9,3,1,2

In [28]:
print(x_train['Item_Identifier'][0])
x_train_cat['Item_Identifier'][0]

FDA15

157

In [29]:
x_train_cat.columns

Index(['Item_Identifier', 'Item_Fat_Content', 'Item_Type', 'Outlet_Identifier',
       'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type'],
      dtype='object')

In [30]:
x_train['Item_Identifier'] = x_train_cat['Item_Identifier']
x_train['Item_Fat_Content'] = x_train_cat['Item_Fat_Content']
x_train['Item_Type'] = x_train_cat['Item_Type']
x_train['Outlet_Identifier'] = x_train_cat['Outlet_Identifier']
x_train['Outlet_Size'] = x_train_cat['Outlet_Size']
x_train['Outlet_Location_Type'] = x_train_cat['Outlet_Location_Type']
x_train['Outlet_Type'] = x_train_cat['Outlet_Type']

In [31]:
x_train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,157,9.300,2,0.016047,5,249.8092,10,1999,2,1,2
1,9,5.920,3,0.019278,15,48.2692,4,2009,2,3,3
2,663,17.500,2,0.016760,11,141.6180,10,1999,2,1,2
3,1122,19.200,3,0.000000,7,182.0950,1,1998,2,3,1
4,1298,8.930,2,0.000000,10,53.8614,2,1987,1,3,2
5,759,10.395,3,0.000000,1,51.4008,4,2009,2,3,3
6,697,13.650,3,0.012741,14,57.6588,2,1987,1,3,2
7,739,NaN,2,0.127470,14,107.7622,6,1985,2,3,4
8,441,16.200,3,0.016687,6,96.9726,8,2002,2,2,2
9,991,19.200,3,0.094450,6,187.8214,3,2007,2,2,2
10,1172,11.800,2,0.000000,7,45.5402,10,1999,2,1,2
11,148,18.500,3,0.045464,5,144.1102,9,1997,3,1,2
12,1143,15.100,3,0.100014,7,145.4786,10,1999,2,1,2
13,905,17.600,3,0.047257,14,119.6782,9,1997,3,1,2
14,376,16.350,2,0.068024,7,196.4426,2,1987,1,3,2
15,768,9.000,3,0.069089,3,56.3614,9,1997,3,1,2
16,1281,11.800,2,0.008596,9,115.3492,4,2009,2,3,3
17,768,9.000,3,0.069196,3,54.3614,10,1999,2,1,2
18,80,NaN,2,0.034238,8,113.2834,6,1985,2,3,4
19,969,13.350,2,0.102492,5,230.5352,7,2004,3,2,2
20,667,18.850,3,0.138190,14,250.8724,2,1987,1,3,2
21,1077,NaN,3,0.035400,1,144.5444,6,1985,2,3,4
22,1279,14.600,2,0.025698,10,196.5084,7,2004,3,2,2
23,260,NaN,2,0.057557,1,107.6938,5,1985,3,1,1
24,844,13.850,3,0.025896,6,165.0210,9,1997,3,1,2
25,1295,13.000,2,0.099887,10,45.9060,3,2007,2,2,2
26,1025,7.645,3,0.066693,14,42.3112,7,2004,3,2,2
27,102,11.650,4,0.019356,8,39.1164,2,1987,1,3,2
28,351,5.925,3,0.161467,5,45.5086,1,1998,2,3,1
29,245,NaN,3,0.072222,4,43.6454,5,1985,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...
8493,747,7.420,3,0.025886,14,189.1872,3,2007,2,2,2
8494,1351,15.200,2,0.000000,10,110.4912,3,2007,2,2,2
8495,331,9.695,2,0.029567,14,160.4920,7,2004,3,2,2
8496,541,7.420,3,0.021696,13,185.3582,3,2007,2,2,2
8497,923,13.650,2,0.049209,7,150.0050,7,2004,3,2,2
8498,1451,15.350,2,0.035293,10,124.5730,4,2009,2,3,3
8499,1374,11.600,2,0.037574,9,100.0042,7,2004,3,2,2
8500,1462,20.350,2,0.000000,10,125.1678,3,2007,2,2,2
8501,1084,5.340,3,0.005998,14,100.4358,3,2007,2,2,2
8502,1340,8.420,2,0.070712,10,216.4192,8,2002,2,2,2
8503,807,20.500,2,0.036133,7,120.1756,7,2004,3,2,2
8504,1411,NaN,2,0.124111,10,111.7544,6,1985,2,3,4
8505,225,10.500,3,0.094146,14,210.8244,4,2009,2,3,3
8506,46,17.250,2,0.084676,15,263.1910,4,2009,2,3,3
8507,672,5.880,3,0.030242,6,101.7990,7,2004,3,2,2
8508,1092,11.350,3,0.043246,7,199.4742,8,2002,2,2,2
8509,421,8.100,2,0.214306,7,213.9902,1,1998,2,3,1
8510,690,13.800,3,0.056862,14,231.5984,7,2004,3,2,2
8511,360,17.500,2,0.026980,6,262.5910,4,2009,2,3,3
8512,842,20.700,2,0.042801,5,178.3028,2,1987,1,3,2
8513,450,12.000,3,0.020407,11,99.9042,7,2004,3,2,2
8514,146,15.000,3,0.054489,4,57.5904,8,2002,2,2,2
8515,446,20.700,2,0.021518,1,157.5288,4,2009,2,3,3
8516,1357,18.600,2,0.118661,12,58.7588,4,2009,2,3,3
8517,390,20.750,5,0.083607,6,178.8318,9,1997,3,1,2
8518,371,6.865,2,0.056783,14,214.5218,2,1987,1,3,2
8519,898,8.380,3,0.046982,1,108.1570,8,2002,2,2,2
8520,1358,10.600,2,0.035186,9,85.1224,7,2004,3,2,2
8521,682,7.210,3,0.145221,14,103.1332,4,2009,2,3,3
8522,51,14.800,2,0.044878,15,75.4670,9,1997,3,1,2

In [32]:
x_train.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                     0
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [33]:
x_train=x_train.fillna(x_train['Item_Weight'].value_counts().index[0])

In [34]:
x_train.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
dtype: int64

In [35]:
x_train.isna().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
dtype: int64

In [36]:
x_train

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,157,9.300,2,0.016047,5,249.8092,10,1999,2,1,2
1,9,5.920,3,0.019278,15,48.2692,4,2009,2,3,3
2,663,17.500,2,0.016760,11,141.6180,10,1999,2,1,2
3,1122,19.200,3,0.000000,7,182.0950,1,1998,2,3,1
4,1298,8.930,2,0.000000,10,53.8614,2,1987,1,3,2
5,759,10.395,3,0.000000,1,51.4008,4,2009,2,3,3
6,697,13.650,3,0.012741,14,57.6588,2,1987,1,3,2
7,739,12.150,2,0.127470,14,107.7622,6,1985,2,3,4
8,441,16.200,3,0.016687,6,96.9726,8,2002,2,2,2
9,991,19.200,3,0.094450,6,187.8214,3,2007,2,2,2
10,1172,11.800,2,0.000000,7,45.5402,10,1999,2,1,2
11,148,18.500,3,0.045464,5,144.1102,9,1997,3,1,2
12,1143,15.100,3,0.100014,7,145.4786,10,1999,2,1,2
13,905,17.600,3,0.047257,14,119.6782,9,1997,3,1,2
14,376,16.350,2,0.068024,7,196.4426,2,1987,1,3,2
15,768,9.000,3,0.069089,3,56.3614,9,1997,3,1,2
16,1281,11.800,2,0.008596,9,115.3492,4,2009,2,3,3
17,768,9.000,3,0.069196,3,54.3614,10,1999,2,1,2
18,80,12.150,2,0.034238,8,113.2834,6,1985,2,3,4
19,969,13.350,2,0.102492,5,230.5352,7,2004,3,2,2
20,667,18.850,3,0.138190,14,250.8724,2,1987,1,3,2
21,1077,12.150,3,0.035400,1,144.5444,6,1985,2,3,4
22,1279,14.600,2,0.025698,10,196.5084,7,2004,3,2,2
23,260,12.150,2,0.057557,1,107.6938,5,1985,3,1,1
24,844,13.850,3,0.025896,6,165.0210,9,1997,3,1,2
25,1295,13.000,2,0.099887,10,45.9060,3,2007,2,2,2
26,1025,7.645,3,0.066693,14,42.3112,7,2004,3,2,2
27,102,11.650,4,0.019356,8,39.1164,2,1987,1,3,2
28,351,5.925,3,0.161467,5,45.5086,1,1998,2,3,1
29,245,12.150,3,0.072222,4,43.6454,5,1985,3,1,1
...,...,...,...,...,...,...,...,...,...,...,...
8493,747,7.420,3,0.025886,14,189.1872,3,2007,2,2,2
8494,1351,15.200,2,0.000000,10,110.4912,3,2007,2,2,2
8495,331,9.695,2,0.029567,14,160.4920,7,2004,3,2,2
8496,541,7.420,3,0.021696,13,185.3582,3,2007,2,2,2
8497,923,13.650,2,0.049209,7,150.0050,7,2004,3,2,2
8498,1451,15.350,2,0.035293,10,124.5730,4,2009,2,3,3
8499,1374,11.600,2,0.037574,9,100.0042,7,2004,3,2,2
8500,1462,20.350,2,0.000000,10,125.1678,3,2007,2,2,2
8501,1084,5.340,3,0.005998,14,100.4358,3,2007,2,2,2
8502,1340,8.420,2,0.070712,10,216.4192,8,2002,2,2,2
8503,807,20.500,2,0.036133,7,120.1756,7,2004,3,2,2
8504,1411,12.150,2,0.124111,10,111.7544,6,1985,2,3,4
8505,225,10.500,3,0.094146,14,210.8244,4,2009,2,3,3
8506,46,17.250,2,0.084676,15,263.1910,4,2009,2,3,3
8507,672,5.880,3,0.030242,6,101.7990,7,2004,3,2,2
8508,1092,11.350,3,0.043246,7,199.4742,8,2002,2,2,2
8509,421,8.100,2,0.214306,7,213.9902,1,1998,2,3,1
8510,690,13.800,3,0.056862,14,231.5984,7,2004,3,2,2
8511,360,17.500,2,0.026980,6,262.5910,4,2009,2,3,3
8512,842,20.700,2,0.042801,5,178.3028,2,1987,1,3,2
8513,450,12.000,3,0.020407,11,99.9042,7,2004,3,2,2
8514,146,15.000,3,0.054489,4,57.5904,8,2002,2,2,2
8515,446,20.700,2,0.021518,1,157.5288,4,2009,2,3,3
8516,1357,18.600,2,0.118661,12,58.7588,4,2009,2,3,3
8517,390,20.750,5,0.083607,6,178.8318,9,1997,3,1,2
8518,371,6.865,2,0.056783,14,214.5218,2,1987,1,3,2
8519,898,8.380,3,0.046982,1,108.1570,8,2002,2,2,2
8520,1358,10.600,2,0.035186,9,85.1224,7,2004,3,2,2
8521,682,7.210,3,0.145221,14,103.1332,4,2009,2,3,3
8522,51,14.800,2,0.044878,15,75.4670,9,1997,3,1,2

In [37]:
y_train

      Item_Outlet_Sales
0             3735.1380
1              443.4228
2             2097.2700
3              732.3800
4              994.7052
5              556.6088
6              343.5528
7             4022.7636
8             1076.5986
9             4710.5350
10            1516.0266
11            2187.1530
12            1589.2646
13            2145.2076
14            1977.4260
15            1547.3192
16            1621.8888
17             718.3982
18            2303.6680
19            2748.4224
20            3775.0860
21            4064.0432
22            1587.2672
23             214.3876
24            4078.0250
25             838.9080
26            1065.2800
27             308.9312
28             178.4344
29             125.8362
...                 ...
8493          4727.1800
8494          1637.8680
8495          4314.3840
8496          3715.1640
8497          2247.0750
8498          1601.2490
8499          2976.1260
8500          1907.5170
8501          1508.0370
8502          3020.0688
8503          3392.9168
8504          4138.6128
8505          2117.2440
8506          3944.8650
8507           515.9950
8508          2587.9646
8509           424.7804
8510          7182.6504
8511          4207.8560
8512          2479.4392
8513           595.2252
8514           468.7232
8515          1571.2880
8516           858.8820
8517          3608.6360
8518          2778.3834
8519           549.2850
8520          1193.1136
8521          1845.5976
8522           765.6700

[8523 rows x 1 columns]

In [38]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x_train,y_train,test_size=0.2, random_state=0)

In [39]:
model.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [40]:
Y_pred = model.predict(X_test)

In [41]:
model.score(X_test,Y_test)

0.5127950434315045

In [42]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=4)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

lin2 = LinearRegression()
lin2.fit(X_train_poly,Y_train)

Y_pred2 = lin2.predict(X_test_poly)
lin2.score(X_test_poly,Y_test)

0.5523026356831069